### ISSUE TITLE
v2 - Better Naming Schemes

### ISSUE THREAD

**Issue by gouthamkrishnakv** [Synine/sycontainer#1]
Since the version 1.0 is presently out, it would be better if a better naming schemes for the functions can be worked out.

**Comment by AdityaVSM** [comment]
Could you show where do you want the enhancement

**Comment by gouthamkrishnakv** [comment]
I want to be able to get objects directly using a single interface. I would prefer `snake_case` for the functions.

In this, we include all the get objects, wrap all he `get_X` objects directly to the system, preferably called `get_element` or `get_object`, same for `is_X()` to `get_type()` , X determinig the data-type.

**DO ONLY EXTEND THE HEADER FILE RATHER THAN MODIFY IT.** A few of the libraries are presently used in a few other libraries as of now;.
